# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint and test
on:
  - push
  - pull_request
jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # TypeScript types are checked during building so there is no need for a separate step for the check
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-
      - name: Install Node packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
